### ISSUE TITLE
Wrong flow

### ISSUE THREAD

**Issue by ada99** [iVis-at-Bilkent/cytoscape.js-undo-redo#1]
Try to move node up. Press Ctrl+Z.
Repeat few times this actions.
Press Ctrl+Y, Ctrl+Y ...
Node moves up up up, where it was never before.
You should clear tail redo actions.

**Comment by selimfirat** [comment]
Now, it seems fixed. Thank you for reporting.
Here is the fixed version: https://raw.githubusercontent.com/iVis-at-Bilkent/cytoscape.js-undo-redo/master/cytoscape-undo-redo.js
