### ISSUE TITLE
Update README with the correct package name

### ISSUE THREAD

**Issue by bididev** [iVis-at-Bilkent/cytoscape.js-undo-redo#12]
Cool extension, thank you for it.

I followed the installation guide and ended up installing the wrong package, in `README.md` the extension's name is `cytoscape.js-undo-redo` (which made sense, considering the GitHub repo's name is identical), but that version seems to be deprecated.

The demo at https://rawgit.com/iVis-at-Bilkent/cytoscape.js-undo-redo/master/demo.html uses `cytoscape-undo-redo` and that one seems more mature, I got it working in 2 minutes.

**Comment by hasanbalci** [comment]
@Raven0us Thanks for the notice. I updated README in the unstable branch. Master branch will also be updated when we make a new release.
