### ISSUE TITLE
ur.reset typo

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-undo-redo#15]
hi folks,

in the reset function the redoStack is loaded with the undos instead of the redos.

cheers

--
//resets undo and redo stacks
instance.reset = function(undos, redos)
{
  this.undoStack = undos || [];
  this.redoStack = undos || [];
}

**Comment by hasanbalci** [comment]
Fixed in unstable branch and will be active with the next release. @shean42 Can you verify and close the issue? Thanks for catching that.

**Comment by shean42** [comment]
looks good, thanks for the update!
