### ISSUE TITLE
Undo / redo for changeParents not working

### ISSUE THREAD

**Issue by Rgtemze** [iVis-at-Bilkent/cytoscape.js-undo-redo#16]
I am using the latest version of cytoscape.js. I can change the parents using that function but cannot undo and redo it. This might be because of the change in cytoscape's `move` function which used to operate on a clone rather than being in-place.

**Comment by hasanbalci** [comment]
@Rgtemze Can you verify the fix and close the issue?

**Comment by Rgtemze** [comment]
Thanks a lot that worked.
