### ISSUE TITLE
Update cytoscape dependancy information

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/cytoscape.js-undo-redo#17]
No peer dependancy has been mentioned in the package.json file. Cytoscape dependancy should be mentioned here and its different versions should be tested to check if the code runs on those versions. This information should also be updated in the readme file.

**Comment by ugurdogrusoz** [comment]
@MobiZaman pls confirm and close if OK

**Comment by MobiZaman** [comment]
The issue has been resolved.
