### ISSUE TITLE
Using default action "move" to remove nodes' parent isn't undoable

### ISSUE THREAD

**Issue by Suges** [iVis-at-Bilkent/cytoscape.js-undo-redo#23]
Hello there and thanks for this extremely helpful plugin!

If you do:
```js
ur.do(
  'move',
  {
    eles: cy.$(':selected'),
    location: { parent: null }
  }
)
```
...undoing after doesn't "do" anything. The reason you would want to do this is to pop nodes out of a compound node.

**Comment by hasanbalci** [comment]
Hi @Suges , 
Yes, I confirm your issue. It seems that the default action `move` currently does a better job for moving edge endpoints. You can instead use the default action `changeParent` to change parents of the nodes, which I believe works more consistently. 
```js
ur.do(
  'changeParent',
  {
    parentData: null,
    nodes: cy.$(':selected'),
    posDiffX: 0,
    posDiffY: 0,
  }
)
```
See details of the `changeParent` action [here](https://github.com/iVis-at-Bilkent/cytoscape.js-undo-redo#default-actions-undoableredoable).

**Comment by Suges** [comment]
Hi @hasanbalci,

Thank you! Works perfectly.
