### ISSUE TITLE
Undo of move nodes is not working when cy instance is reloaded

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/cytoscape.js-undo-redo#3]
Please see the following issue 'https://github.com/iVis-at-Bilkent/sbgnviz-js/issues/155'. I think that this issue is not application specific. I think that it is caused by the following reason. When a new cy instance is loaded old cy events are removed (I am not sure but it seems to be so) and they are needed to be redefined. However, 'isInitialized' flag in this extension keeps its old value. And if this flag is true the default "setDragUndo()" is not called and so the things to be done on "mousedown", "mouseup" etc. are not redefined by this extension.

**Comment by selimfirat** [comment]
After the commit above, it seems fixed (in sbgn-viz too). I also published to npm.

**Comment by metincansiper** [comment]
Thanks, it seems to be fixed.
