### ISSUE TITLE
Undo/Redo Stack Limit

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-undo-redo#4]
hi guys, 

one feature which imho would be useful is an additional init option to limit the size of the undo/redo stack. during long edit sessions in complex graphs this would help to limit memory usage and thus minimize the risk of browser crashes!

anyway great extension, thanks for providing! :-)

**Comment by metincansiper** [comment]
@shean42 thanks for this suggestion. I added 'stackSizeLimit' option, which is undefined by default and there is no limit for stack size if this option is undefined. I am closing the issue for now, please let me knwo if you see any problem with this.
