### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-undo-redo#5]
What is the license of the extension? I'd assume it is the same as cy.js but in order to avoid confusion it would be great if this could be explicitly stated by integration a license file or similar. This actually is a question of mine with respect to all extensions from your organization :-)

Thanks for clarifying this!!

**Comment by ugurdogrusoz** [comment]
Yes, our Cytoscape.js extensions are distributed under the same license (The MIT License) as Cytoscape.js. We now have this specified in our README files. Thanks for pointing out.
